const { default: processMessage } = require('@whiskeysockets/baileys/lib/Utils/process-message');

require('dotenv').config({ path: './config.env' });
module.exports = {
  VERSION: require('./package.json').version,
  session: (process.env.SESSION_ID || ''),
  DATABASE_URL: process.env.DATABASE || './config/database.db',
  PREFIX: (process.env.PREFIX || '&').trim(),
  SUDO: process.env.SUDO || '',
  DATABASE: process.env.DATABASE_URL || '',
  MENU_TOP_LEFT: process.env.MENU_TOP_LEFT ||'┌─❖',
  MENU_BOT_NAME_LINE: process.env.MENU_BOT_NAME_LINE || '│ ',
  MENU_BOTTOM_LEFT: process.env.MENU_BOTTOM_LEFT ||'└┬❖',
  MENU_GREETING_LINE: process.env.MENU_GREETING_LINE || '┌┤ ',
  MENU_DIVIDER: process.env.MENU_DIVIDER ||'│└────────┈⳹',
  MENU_USER_LINE: process.env.MENU_USER_LINE || '│🕵️ ',
  MENU_DATE_LINE: process.env.MENU_DATE_LINE ||'│📅 ',
  MENU_TIME_LINE: process.env.MENU_TIME_LINE || '│⏰ ',
  MENU_STATS_LINE: process.env.MENU_STATS_LINE || '│⭐ ',
  MENU_BOTTOM_DIVIDER: process.env.MENU_BOTTOM_DIVIDER ||'└─────────────┈⳹',
  FOOTER: process.env.FOOTER || '\n\nFor more info visit: bwmxmd.online\n\n®2025 ʙᴡᴍ xᴍᴅ 🔥',
  OWNER_NAME: process.env.OWNER_NAME || 'Lee Ezra',
  OWNER_NUMBER: process.env.OWNER_NUMBER ||'254716410122',
  AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || 'no',
  AUTO_DOWNLOAD_STATUS: process.env.AUTO_DOWNLOAD_STATUS || 'no',
  BOT: process.env.BOT || 'Hot Bot',
  URL: process.env.URL || 'https://files.catbox.moe/h2ydge.jpg',
  GURL: process.env.GURL || '',        
  AUTO_REPLY_STATUS: process.env.AUTO_REPLY_STATUS || 'no',
  MODE: process.env.MODE || 'yes',
  PM_PERMIT: process.env.PM_PERMIT || 'yes',
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || undefined,
  HEROKU_APY_KEY: process.env.HEROKU_API_KEY || undefined,
  WARN_COUNT: process.env.WARN_COUNT || '3',
  ETAT: process.env.PRESENCE || '3',
  CHATBOT: process.env.CHATBOT || 'no',
  CHATBOT1: process.env.CHATBOT1 || 'no',
  DP: process.env.DP || 'yes',
  ANTIDELETE1: process.env.ANTIDELETE1 || 'no',
  ANTIDELETE2: process.env.ANTIDELETE2 || 'no',
  GOODBYE_MESSAGE: process.env.GOODBYE_MESSAGE || 'no',
  ANTICALL: process.env.ANTICALL || 'no',
  WELCOME_MESSAGE: process.env.WELCOME_MESSAGE || 'no',
  GROUP_ANTILINK2: process.env.GROUP_ANTILINK2 || 'no',
  GROUP_ANTILINK: process.env.GROUP_ANTILINK || 'no',
  STATUS_REACT_EMOJIS: process.env.STATUS_REACT_EMOJIS ||'null',
  REPLY_STATUS_TEXT: process.env.REPLY_STATUS_TEXT || '',
  AUTO_REACT: process.env.AUTO_REACT || 'no',
  AUTO_REACT_STATUS: process.env.AUTO_REACT_STATUS || 'no',
  AUTO_REPLY: process.env.AUTO_REPLY || 'no',
  AUTO_READ: process.env.AUTO_READ || 'no',
  AUTO_SAVE_CONTACTS: process.env.AUTO_SAVE_CONTACTS || 'yes',
  AUTO_REJECT_CALL: process.env.AUTO_REJECT_CALL || 'yes',
  AUTO_BIO: process.env.AUTO_BIO || 'no',
  AUDIO_REPLY: process.env.AUDIO_REPLY || 'no',
  BOT_URL: process.env.BOT_URL || [
    'https://res.cloudinary.com/dptzpfgtm/image/upload/v1748879883/whatsapp_uploads/e3eprzkzxhwfx7pmemr5.jpg',
    'https://res.cloudinary.com/dptzpfgtm/image/upload/v1748879901/whatsapp_uploads/hqagxk84idvf899rhpfj.jpg',
    'https://res.cloudinary.com/dptzpfgtm/image/upload/v1748879921/whatsapp_uploads/bms318aehnllm6sfdgql.jpg'
  ],
}